version: "3.4"
services:
  timesheets-api:
    container_name: timesheets-api
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./Timesheets:/api
    working_dir: /api
    command: "dotnet run"
    ports:
      - "8001:8081"

  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - .:/src
      - ../test:/test
    working_dir: /src
    command: "dotnet test ./Example.Service.sln --no-restore"
    depends_on:
     - timesheets-api