version: "3.4"
services:
  timesheets-api:
    container_name: timesheets-api
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./src:/src
    working_dir: /src
    command: "dotnet run"
    ports:
      - "5000:80"

  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./src:/src
      - ./test:/test
    working_dir: /
    command: "dotnet test --no-restore"
    depends_on:
     - timesheets-api