version: "3.4"
services:
  example-service:
    image: example-service
    build:
      context: ../../
      dockerfile: src/Example.Service/Dockerfile
    ports:
      - "5000:80"

  integration-tests:
    image: integration-tests
    build:
      context: ../../
      dockerfile: test/Example.Service.ComponentTest/Dockerfile
    entrypoint: dotnet test --logger trx --results-directory /var/temp
    volumes:
        - /opt/vsts/work/_temp:/var/temp
    depends_on: 
        - example-service