version: "3.4"
services:
  timesheets-api:
    container_name: timesheets-api
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./Timesheets:/api
    working_dir: /api
    command: "dotnet run"
    depends_on:
     - sql-server-database
    ports:
      - "8001:8081"

  sql-server-database:
    container_name: sql-server-database
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 1AvenueCodePassword*
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - .:/src
      - ../test:/test
    working_dir: /src
    command: 
        [
        "./Scripts/wait-for-it.sh",
        "sql-server-database:1433",
        "--",
        "dotnet",
        "test"
      ]
    depends_on:
     - timesheets-api