version: "3.4"
services:
  timesheets-api:
    container_name: timesheets-api
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ../../src:/src
    working_dir: /src
    command: "dotnet run"
    ports:
      - "5000:80"

  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ../..:/solution
    working_dir: /solution
    command: "dotnet test ./test/Example.Service.UnitTest/Example.Service.UnitTest.csproj"
    depends_on:
     - timesheets-api