version: "3.4"
services:
  timesheets-api:
    container_name: timesheets-api
    image: example-api
    build:
      context: ../../
      dockerfile: /src/Example.Service/Dockerfile
    ports:
      - "5000:80"

  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ../..:/solution
    working_dir: /solution
    command: "dotnet test"
    depends_on:
     - timesheets-api
